In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [30]:
df = pd.read_csv("pima_indian_diabetes.csv")

In [31]:
df.head()

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP  Triceps  Insulin   BMI  \
0                  1              89            66       23       94  28.1   
1                  0             137            40       35      168  43.1   
2                  3              78            50       32       88  31.0   
3                  2             197            70       45      543  30.5   
4                  1             189            60       23      846  30.1   

   Age  Diabetes  
0   21         0  
1   33         1  
2   26         1  
3   53         1  
4   59         1

In [32]:
y = df['Diabetes']
X = df.drop(['Diabetes'], axis=1)

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.3,random_state=100)

In [34]:
X_train

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP  Triceps  Insulin   BMI  \
169                  9             152            78       34      171  34.2   
265                  6             129            90        7      326  19.6   
386                  1             121            78       39       74  39.0   
241                  6             154            78       41      140  46.1   
249                  1             139            62       41      480  40.7   
..                 ...             ...           ...      ...      ...   ...   
343                  1             112            80       45      132  34.8   
359                  4             127            88       11      155  34.5   
323                  1             128            82       17      183  27.5   
280                  8             186            90       35      225  34.5   
8                    1             115            70       30       96  34.6   

     Age  
169   33  
265   60  
386   28  
241   27  
249   21  
..   ...  
343   24  
359   28  
323   22  
280   37  
8     32  

[274 rows x 7 columns]

In [35]:
X_test

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP  Triceps  Insulin   BMI  \
124                 11             155            76       28      150  33.3   
140                  0             107            62       30       74  36.6   
276                  8             100            74       40      215  39.4   
252                  4             125            70       18      122  28.9   
326                  1             100            74       12       46  19.5   
..                 ...             ...           ...      ...      ...   ...   
332                 11             136            84       35      130  28.3   
15                   3              88            58       11       54  24.8   
33                   4             129            86       20      270  35.1   
171                  1              95            74       21       73  25.9   
355                  2             121            70       32       95  39.1   

     Age  
124   51  
140   25  
276   43  
252   45  
326   28  
..   ...  
332   42  
15    22  
33    23  
171   36  
355   23  

[118 rows x 7 columns]

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train[:] = scaler.fit_transform(X_train[:])


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [37]:
X_train

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP   Triceps   Insulin  \
169           1.815945        0.957700      0.567715  0.470846  0.087700   
265           0.873580        0.211296      1.537905 -2.077303  1.358030   
386          -0.697030       -0.048323      0.567715  0.942726 -0.707281   
241           0.873580        1.022605      0.567715  1.131478 -0.166366   
249          -0.697030        0.535819     -0.725872  1.131478  2.620165   
..                 ...             ...           ...       ...       ...   
343          -0.697030       -0.340394      0.729413  1.508981 -0.231932   
359           0.245336        0.146391      1.376207 -1.699800 -0.043431   
323          -0.697030        0.178843      0.891112 -1.133544  0.186048   
280           1.501824        2.061080      1.537905  0.565222  0.530266   
8            -0.697030       -0.243037     -0.079079  0.093343 -0.526976   

          BMI       Age  
169  0.124473  0.279158  
265 -1.912926  3.018166  
386  0.794302 -0.228066  
241  1.785092 -0.329510  
249  1.031534 -0.938179  
..        ...       ...  
343  0.208201 -0.633844  
359  0.166337 -0.228066  
323 -0.810498 -0.836734  
280  0.166337  0.684937  
8    0.180292  0.177713  

[274 rows x 7 columns]

In [38]:
X_train.describe()

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP       Triceps  \
count       2.740000e+02    2.740000e+02  2.740000e+02  2.740000e+02   
mean        2.998413e-17   -6.797077e-17 -3.515537e-16 -1.348273e-16   
std         1.001830e+00    1.001830e+00  1.001830e+00  1.001830e+00   
min        -1.011151e+00   -2.157727e+00 -3.313046e+00 -2.077303e+00   
25%        -6.970296e-01   -7.622751e-01 -7.258723e-01 -8.268226e-01   
50%        -3.829077e-01   -1.132279e-01  1.770420e-03 -1.033313e-03   
75%         5.594579e-01    6.656287e-01  7.294132e-01  7.539740e-01   
max         4.328920e+00    2.385604e+00  3.154889e+00  2.924620e+00   

            Insulin           BMI           Age  
count  2.740000e+02  2.740000e+02  2.740000e+02  
mean   2.188031e-17  6.229810e-16 -6.756558e-17  
std    1.001830e+00  1.001830e+00  1.001830e+00  
min   -1.190826e+00 -2.108294e+00 -9.381786e-01  
25%   -6.744984e-01 -6.569955e-01 -7.352891e-01  
50%   -2.770080e-01 -1.120457e-03 -4.309550e-01  
75%    2.721025e-01  5.605598e-01  4.820476e-01  
max    5.619783e+00  4.715598e+00  3.322500e+00

In [45]:
from sklearn import svm
clf = svm.SVC(C=1,kernel="rbf")
clf.fit(X_train,y_train)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [46]:
y_train_pred = clf.predict(X_train)

In [47]:
from sklearn.metrics import classification_report
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.87      0.93      0.90       182
           1       0.84      0.72      0.77        92

    accuracy                           0.86       274
   macro avg       0.85      0.82      0.83       274
weighted avg       0.86      0.86      0.85       274



In [48]:
X_test[:] = scaler.transform(X_test[:])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [49]:
y_test_pred = clf.predict(X_test)

In [50]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.80      0.85      0.82        80
           1       0.64      0.55      0.59        38

    accuracy                           0.75       118
   macro avg       0.72      0.70      0.71       118
weighted avg       0.75      0.75      0.75       118



In [51]:
clf.support_

array([  1,   2,   3,   4,   6,   8,  12,  16,  18,  23,  29,  32,  34,
        38,  39,  42,  43,  45,  49,  52,  54,  58,  60,  61,  62,  64,
        66,  71,  81,  90,  91,  92,  94, 116, 118, 124, 130, 132, 134,
       135, 137, 138, 147, 148, 151, 153, 160, 166, 167, 170, 171, 177,
       179, 182, 187, 195, 198, 199, 202, 209, 211, 213, 215, 217, 222,
       223, 224, 228, 229, 232, 241, 249, 254, 258, 259, 267, 269, 270,
         0,   7,  14,  15,  17,  19,  26,  28,  30,  37,  40,  41,  44,
        48,  50,  57,  65,  68,  76,  79,  80,  84,  85,  89,  96,  98,
       100, 101, 107, 110, 111, 113, 121, 123, 131, 133, 142, 143, 145,
       149, 150, 152, 154, 156, 159, 164, 165, 173, 176, 180, 184, 190,
       193, 200, 204, 205, 214, 216, 233, 236, 238, 240, 243, 244, 246,
       247, 248, 250, 251, 252, 256, 257, 262, 265, 266, 273], dtype=int32)

In [53]:
clf.support_vectors_

array([[ 0.87357982,  0.21129566,  1.53790507, ...,  1.35802998,
        -1.91292648,  3.01816563],
       [-0.69702957, -0.04832322,  0.56771477, ..., -0.70728111,
         0.79430249, -0.22806551],
       [ 0.87357982,  1.02260465,  0.56771477, ..., -0.1663663 ,
         1.78509247, -0.32951023],
       ...,
       [ 1.1877017 ,  1.21731881, -1.37266585, ...,  0.12048246,
        -0.39185453,  0.88782645],
       [-0.69702957,  0.69808105,  0.89111154, ...,  0.16146086,
         1.78509247,  1.59793951],
       [-0.69702957, -0.24303738, -0.07907877, ..., -0.52697617,
         0.18029179,  0.17771338]])

In [54]:
clf.n_support_

array([78, 76], dtype=int32)

In [55]:
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_train,y_train_pred)

In [56]:
confusion

array([[169,  13],
       [ 26,  66]])